name: 'Shipi18n Auto Translate'
description: 'Automatically translate your i18n locale files using Shipi18n API'
author: 'Shipi18n'
branding:
  icon: 'globe'
  color: 'blue'

inputs:
  api-key:
    description: 'Shipi18n API key'
    required: true
  source-file:
    description: 'Path to source locale file (e.g., locales/en.json). Use this OR source-dir.'
    required: false
    default: ''
  source-dir:
    description: 'Path to source locale directory (e.g., locales/en). All JSON/YAML files will be translated. Use this OR source-file.'
    required: false
    default: ''
  target-languages:
    description: 'Comma-separated list of target language codes (e.g., es,fr,de)'
    required: true
  output-dir:
    description: 'Directory to output translated files (default: same as source file directory)'
    required: false
    default: ''
  source-language:
    description: 'Source language code (default: en)'
    required: false
    default: 'en'
  create-pr:
    description: 'Create a pull request instead of direct commit (true/false)'
    required: false
    default: 'false'
  commit-message:
    description: 'Custom commit message (default: "chore: update translations [skip ci]")'
    required: false
    default: 'chore: update translations [skip ci]'
  branch-name:
    description: 'Branch name for PR (only used if create-pr is true)'
    required: false
    default: 'shipi18n-translations'
  github-token:
    description: 'GitHub token for creating PRs (defaults to GITHUB_TOKEN)'
    required: false
    default: ''

outputs:
  files-changed:
    description: 'Number of translation files updated'
  files-list:
    description: 'JSON array of files that were translated'
  languages:
    description: 'List of languages translated'

runs:
  using: 'node20'
  main: 'dist/index.js'
